name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Testing
        run: npm test
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TOKEN: ${{ secrets.TOKEN }}
